export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Landing } from "../pages/Landing";
export { default as About } from "../pages/About";
export { default as SignIn } from "../pages/SignIn";
export { default as SignUp } from "../pages/SignUp";
export { default as AddRecipe } from "../pages/AddRecipe";
export { default as ViewRecipe } from "../pages/ViewRecipe";
export { default as MyRecipes } from "../pages/MyRecipes";